services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=ssm
      - DEBUG=0
      - LS_LOG=warn
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
    volumes:
      - ./localstack:/var/lib/localstack
    healthcheck:
      test:
        [
          "CMD",
          "bash",
          "-c",
          "awslocal ssm list-parameters >/dev/null 2>&1 || exit 1",
        ]
      interval: 5s
      timeout: 3s
      retries: 20
